# Site settings

title: ndom91 [mis]adventures

#description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ndo.dev # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# Jekyll reload command:
#
#      sudo jekyll build --verbose --destination /var/www/html/particle --watch

# User settings
username: Nico Domino
user_description: Web Dev
user_title: Web Dev
email: yo@ni.co.de
twitter_username: ndom91
github_username: ndom91

# Google-analytics
google-analytics:
  id: "UA-111339084-2"

exclude: ['package.json', 'src' , 'node_modules']

permalink: _posts/:year-:month-:day-:title.md.html

excerpt_seperator: <!---excerpt--->

plugins:
  - "disqus-for-jekyll"
  - "jekyll-paginate-v2"

blogid: "#blog"

pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# disqus:
  # name: "iamnico-xyz" # required
  # noscript: "no script :(" # optional
